version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/home/jenkins/volumes/var/jenkins:/var/jenkins_home'
      - '/home/jenkins/volumes/var/run/docker.sock:/var/run/docker.sock'
      - '/home/jenkins/volumes/usr/local/bin/docker:/usr/local/bin/docker'
      - '/var/run/docker.sock:/var/run/docker.sock'
